//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sabzify
{


    public partial class AddAddress
    {
        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>
        /// rfvFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;

        /// <summary>
        /// revFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revFullName;

        /// <summary>
        /// ddlCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlCode;

        /// <summary>
        /// txtPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        /// <summary>
        /// rfvPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPhone;

        /// <summary>
        /// revPhone control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPhone;

        /// <summary>
        /// txtBuilding control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuilding;

        /// <summary>
        /// rfvBuilding control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvBuilding;

        /// <summary>
        /// revBuilding control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revBuilding;

        /// <summary>
        /// txtArea control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtArea;

        /// <summary>
        /// rfvArea control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvArea;

        /// <summary>
        /// revArea control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revArea;

        /// <summary>
        /// txtLandmark control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLandmark;

        /// <summary>
        /// revLandmark control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revLandmark;

        /// <summary>
        /// txtPincode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPincode;

        /// <summary>
        /// rfvPincode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPincode;

        /// <summary>
        /// revPincode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPincode;

        /// <summary>
        /// txtCity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCity;

        /// <summary>
        /// rfvCity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCity;

        /// <summary>
        /// revCity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revCity;

        /// <summary>
        /// ddlState control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlState;

        /// <summary>
        /// rfvState control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvState;

        /// <summary>
        /// rbHome control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton rbHome;

        /// <summary>
        /// rbOffice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton rbOffice;

        /// <summary>
        /// rbOther control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton rbOther;

        /// <summary>
        /// chkDefault control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkDefault;

        /// <summary>
        /// vsAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ValidationSummary vsAddress;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
