//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sabzify
{


    public partial class Cart
    {
        /// <summary>
        /// txtQtyCarrot control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQtyCarrot;

        /// <summary>
        /// rfvQtyCarrot control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQtyCarrot;

        /// <summary>
        /// rvQtyCarrot control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvQtyCarrot;

        /// <summary>
        /// txtQtyBroccoli control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQtyBroccoli;

        /// <summary>
        /// rfvQtyBroccoli control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQtyBroccoli;

        /// <summary>
        /// rvQtyBroccoli control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvQtyBroccoli;

        /// <summary>
        /// vsCart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ValidationSummary vsCart;

        /// <summary>
        /// btnCheckout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCheckout;
    }
}
