//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sabzify
{


    public partial class ProductDetails
    {
        /// <summary>
        /// txtQty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQty;

        /// <summary>
        /// btnAddToCart control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddToCart;

        /// <summary>
        /// btnBuyNow control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuyNow;

        /// <summary>
        /// rfvQty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQty;

        /// <summary>
        /// rvQty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvQty;
    }
}
