//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sabzify
{


    public partial class Vegetables
    {
        /// <summary>
        /// txtQtyCarrot control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQtyCarrot;

        /// <summary>
        /// rfvQtyCarrot control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQtyCarrot;

        /// <summary>
        /// rvQtyCarrot control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvQtyCarrot;

        /// <summary>
        /// txtQtyTomato control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQtyTomato;

        /// <summary>
        /// rfvQtyTomato control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQtyTomato;

        /// <summary>
        /// rvQtyTomato control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvQtyTomato;

        /// <summary>
        /// txtQtyPotato control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQtyPotato;

        /// <summary>
        /// rfvQtyPotato control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQtyPotato;

        /// <summary>
        /// rvQtyPotato control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvQtyPotato;

        /// <summary>
        /// txtQtyPalak control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtQtyPalak;

        /// <summary>
        /// rfvQtyPalak control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvQtyPalak;

        /// <summary>
        /// rvQtyPalak control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvQtyPalak;
    }
}
